### ISSUE TITLE
Synthetic Dataset "guess_correctness"

### ISSUE THREAD

**Issue by lazyeden** [eth-sri/llmprivacy#2]
Could you tell me the meaning of "model_free_eval" and "model_aided_eval" fields of "guess_correctness" in synthetic dataset?

**Comment by mveroe** [comment]
"model_free_eval" contains the evaluation of the guess correctness based solely on manual checks, while "model_aided_eval" contains the evaluations corrected by GPT4. src/synthetic/eval_tools.py should give you some more insight in the details of how these two methods work.
