### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'parsing/pobp.csv'

### ISSUE THREAD

**Issue by Dora238** [eth-sri/llmprivacy#4]
Hello,

While using your `Dataset` class, I encountered a `FileNotFoundError` for `parsing/pobp.csv`. Here's the traceback for the error:

FileNotFoundError: [Errno 2] No such file or directory: 'parsing/pobp.csv'

This file seems crucial to properly initialize the Dataset class as it loads information into pobp_mapping.

Can you kindly look into this problem or provide guidance about acquiring the file?

Thanks in advance for your assistance!

**Comment by RobinStaab** [comment]
Hey,

Sorry, these files apparently got excluded by an over-eager `.gitignore`. I have included them all in the last commit :) 

Best Wishes,
Robin

**Comment by Dora238** [comment]
Thanks for the response, I will close this issue.
